# nixpacks.toml - Railway Build Configuration
[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "cd backend && python railway_start.py"
