# nixpacks.toml - Railway Build Configuration
[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "python312Packages.setuptools", "python312Packages.wheel"]

[phases.install] 
cmds = ["pip install --upgrade pip setuptools wheel", "pip install --no-cache-dir -r requirements-minimal.txt"]

[start]
cmd = "cd backend && python railway_start.py"
